# Generated by Django 3.0 on 2021-04-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210407_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
